### ISSUE TITLE
Importing ORTModelForFeatureExtraction fails with ImportError: libcuda.so.1 on CPU

### ISSUE THREAD

**Issue by maziyarpanahi** [huggingface/optimum#1619]
### System Info

```shell
- Latest optimum for onnxruntime
- Everything else is a default on Google Colab
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction (minimal, reproducible, runnable)

- Google Colab
- CPU runtime
- This code:
```
!pip install --upgrade-strategy eager install optimum[onnxruntime]
from optimum.onnxruntime import ORTModelForFeatureExtraction
```

Will result in the following error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/cupy/__init__.py](https://ukwaaqc7ito-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231219-060136_RC00_592175853#) in <module>
     16 try:
---> 17     from cupy import _core  # NOQA
     18 except ImportError as exc:

16 frames
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
================================================================


The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py](https://ukwaaqc7ito-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231219-060136_RC00_592175853#) in _get_module(self, module_name)
   1353             return importlib.import_module("." + module_name, self.__name__)
   1354         except Exception as e:
-> 1355             raise RuntimeError(
   1356                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
   1357                 f" traceback):\n{e}"

RuntimeError: Failed to import optimum.onnxruntime.modeling_ort because of the following error (look up to see its traceback):

================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
================================================================
```

If you choose `GPU` runtime, running the same exact 2 lines (install and import) works perfectly! It's like something inside `optimum.onnxruntime` requires CUDA even though the `onnxruntime` is for cpu and not `onnxruntime-gpu`.

PS: Link to a reproducible Colab: https://colab.research.google.com/drive/11jRoskoIf1g8AP6DEtzG1bcQqA7pjV-d?usp=sharing

### Expected behavior

I cannot import `ORTModelForFeatureExtraction` from `optimum.onnxruntime` in Google Colab while I am on CPU Runtime. As soon as I switch to GPU runtime, it works!

You should be able to import `ORTModelForFeatureExtraction` from `optimum.onnxruntime` regardless of whether you are on CPU or GPU.

**Comment by fxmarty** [comment]
Thank you for the report @maziyarpanahi, this should be fixed on main. Currently in colab:

```
!rm -rf optimum
!git clone https://github.com/huggingface/optimum.git
!cd optimum && pip uninstall -y optimum && pip install .[onnxruntime]
```

&

```
from optimum.onnxruntime import ORTModelForFeatureExtraction
```

works for me.

**Comment by maziyarpanahi** [comment]
Thanks @fxmarty for your PR, I can confirm installing from the main branch fixes the issue:

<img width="716" alt="image" src="https://github.com/huggingface/optimum/assets/5762953/9d81c4e9-79cf-4f4c-8c01-199dec417232">

Many thanks again 👍🏼

**Comment by regstuff** [comment]
No luck for me. :( Still getting this error. Copy pasted the commands as is.

```
ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/cupy/__init__.py](https://localhost:8080/#) in <module>
     16 try:
---> 17     from cupy import _core  # NOQA
     18 except ImportError as exc:

16 frames
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
================================================================


The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
   1353             return importlib.import_module("." + module_name, self.__name__)
   1354         except Exception as e:
-> 1355             raise RuntimeError(
   1356                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
   1357                 f" traceback):\n{e}"

RuntimeError: Failed to import optimum.onnxruntime.modeling_ort because of the following error (look up to see its traceback):

================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
```

**Comment by fxmarty** [comment]
@regstuff Are you installing from source?

**Comment by regstuff** [comment]
@fxmarty, this is what I did:
```
!rm -rf optimum
!git clone https://github.com/huggingface/optimum.git
!cd optimum && pip uninstall -y optimum && pip install .[onnxruntime]
from optimum.onnxruntime import ORTModelForFeatureExtraction
```

**Comment by fxmarty** [comment]
That's weird, I can not reproduce on a colab :/

**Comment by darien-schettler** [comment]
If I run

```
!rm -rf optimum
!git clone https://github.com/huggingface/optimum.git
!cd optimum && pip uninstall -y optimum && pip install .[onnxruntime]
from optimum.onnxruntime import ORTModelForFeatureExtraction
```

In the top cell of any Colab it produces the error. Is there a proper way to resolve this so that I can use onnx on CPU with colab?

**Comment by virtualramblas** [comment]
Same error here. I believe this issue should be re-opened.

**Comment by maiiabocharova** [comment]
@fxmarty This should be reopened - the error is still there - with the fresh runtime in Colab and installation from source - in CPU runtime of Colab the error is there
