### ISSUE TITLE
onnxruntime-gpu not found

### ISSUE THREAD

**Issue by Eichhof** [huggingface/optimum#769]
### System Info

```shell
Optimum: 1.6.3
Python: 3.10.4
Platform: Windows 10
Cuda: 11.6
```

### Who can help?

@JingyaHuang 
@echarlaix 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I Installed optimum with pip install optimum[onnxruntime-gpu]. Then I was running python -m optimum.exporters.onnx --task causal-lm-with-past --model EleutherAI/gpt-j-6B gptj_onnx/ to transform GPT-J to ONNX. To use the model, I used the following lines:

```
from transformers import AutoTokenizer
from optimum.onnxruntime import ORTModelForCausalLM
import torch

tokenizer = AutoTokenizer.from_pretrained("C:/Users/myUsername/Desktop/gptj_onnx", pad_token=gpt_eos, eos_token=gpt_eos, truncation_side='left')
model = ORTModelForCausalLM.from_pretrained(
            "C:/Users/myUsername/Desktop/gptj_onnx",
            provider="TensorrtExecutionProvider",
            torch_dtype=torch.float16,
            low_cpu_mem_usage=True,
            use_cache=True,
            gradient_checkpointing=gradient_checkpointing
)
```

When using optimum 1.6.0 it works, but with optimum 1.6.3 I'm getting the following error:

```
ImportError: Asked to use TensorrtExecutionProvider, but `onnxruntime-gpu` package was not found. Make sure to install `onnxruntime-gpu` package instead of `onnxruntime`.
```

I have installed Cuda 11.6 and also cuDNN 8.7.0.

### Expected behavior

It should run without an error. onnxruntime-gpu should be found.

**Comment by michaelbenayoun** [comment]
Please check that `onnxruntime` is not also installed. You can fix that by doing:

```bash
pip uninstall onnxruntime
pip uninstall onnxruntime-gpu

pip install onnxruntime-gpu
```

**Comment by Eichhof** [comment]
I did it but it does not work. Only onnxruntime-gpu is installed. With optimum 1.6.0 it works but with optimum 1.6.3 it does not work anymore.

**Comment by fxmarty** [comment]
Hi @Eichhof thanks for the report. It could be related to the fact you are running Windows. Could you run:

```
pip uninstall onnxruntime onnxruntime-gpu && pip install onnxruntime-gpu
```

and then

```python
import onnxruntime as ort

path_cuda_lib = os.path.join(ort.__path__[0], "capi", "libonnxruntime_providers_cuda.so")
path_trt_lib = os.path.join(ort.__path__[0], "capi", "libonnxruntime_providers_tensorrt.so")
path_dependecy_loading = os.path.join(ort.__path__[0], "capi", "_ld_preload.py")

with open(path_dependecy_loading, "r") as f:
    file_string = f.read()
    print(file_string)
```

and report the log? Thank you!

**Comment by Eichhof** [comment]
@fxmarty Here is the output of the log:

```
['C:\\Users\\myUsername\\Anaconda3\\envs\\huggingface\\lib\\site-packages\\onnxruntime']
# -------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# --------------------------------------------------------------------------

# This file can be modified by setup.py when building a manylinux2010 wheel
# When modified, it will preload some libraries needed for the python C extension
```

**Comment by fxmarty** [comment]
Thank you, that's quite surprising. Could you try `pip uninstall onnnxruntime onnxruntime-gpu` and make sure that the folder `C:\\Users\\myUsername\\Anaconda3\\envs\\huggingface\\lib\\site-packages\\onnxruntime` is removed? It feels like an install issue to me.

In Optimum, the file `capi/_ld_preload.py` is used to detect whether `onnxruntime` or `onnxruntime-gpu` is installed. For me with `onnxruntime-gpu` installed it looks like:

```
# -------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# --------------------------------------------------------------------------

# This file can be modified by setup.py when building a manylinux2010 wheel
# When modified, it will preload some libraries needed for the python C extension
from ctypes import CDLL, RTLD_GLOBAL
try:
    _libcublasLt = CDLL("libcublasLt.so.11", mode=RTLD_GLOBAL)
    _libcublas = CDLL("libcublas.so.11", mode=RTLD_GLOBAL)
    _libcudnn = CDLL("libcudnn.so.8", mode=RTLD_GLOBAL)
    _libcurand = CDLL("libcurand.so.10", mode=RTLD_GLOBAL)
    _libcufft = CDLL("libcufft.so.10", mode=RTLD_GLOBAL)
    _libcudart = CDLL("libcudart.so.11.0", mode=RTLD_GLOBAL)
except OSError:
    import os
    os.environ["ORT_CUDA_UNAVAILABLE"] = "1"
from ctypes import CDLL, RTLD_GLOBAL
try:
    _libcudnn = CDLL("libcudnn.so.8", mode=RTLD_GLOBAL)
    _libcublas = CDLL("libcublas.so.11", mode=RTLD_GLOBAL)
    _libcudart = CDLL("libcudart.so.11.0", mode=RTLD_GLOBAL)
    _libnvinfer = CDLL("libnvinfer.so.8", mode=RTLD_GLOBAL)
    _libnvinfer_plugin = CDLL("libnvinfer_plugin.so.8", mode=RTLD_GLOBAL)
except OSError:
    import os
    os.environ["ORT_TENSORRT_UNAVAILABLE"] = "1"
```

**Comment by Eichhof** [comment]
Thank you very much for your help. I checked and `C:\\Users\\myUsername\\Anaconda3\\envs\\huggingface\\lib\\site-packages\\onnxruntime` is removed. It would be great if you could do a PR.

**Comment by fxmarty** [comment]
Hi @Eichhof , it should be fixed with https://github.com/huggingface/optimum/pull/771 . Would you like to check by running temporarily on `main`: `pip install -U git+https://github.com/huggingface/optimum.git@main`? The release should follow shortly.

**Comment by Eichhof** [comment]
Error is resolved. Thank you very much.
